os:
  - linux
language: java
jdk:
  - openjdk11
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - java -version
  - node -v
  - npm -v
install:
  - chmod +x mvnw
  - ./mvnw dependency:go-offline --no-transfer-progress
script:
  - ./mvnw -Pprod verify jib:dockerBuild
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
